spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
server:
  port: 8888
logging:
  level:
    root: ERROR
  file: /tmp/badam7.log

  
